#!/usr/bin/env python3
"""
Quiz Banks Generator for Personal Language Trainer
Generates 100 distinct levels for FoodQuizBank.kt
"""

def escape_kt(text):
    return text.replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$')

# 100 Lessons for Food & Dining
food_topics = [
    # Unit 1: Street Food & Snacks (1-10)
    ("Samosas & Street Snacks", "Samosa", "Crispy fried pastry filled with spiced potatoes and peas",
     "What is a popular triangular crispy fried snack with spiced potato filling?",
     ["Samosa", "Pancake", "Croissant", "Donut"], "Samosa",
     "Samosas are India's iconic triangular street snack served with tangy chutneys.",
     "Bhaiya, please pack two hot samosas with sweet tamarind chutney.",
     "What did the customer order at the street stall?",
     ["Two hot samosas with sweet tamarind chutney", "Ten plates of cold rice", "A glass of black coffee", "Two spicy burgers"],
     "Two hot samosas with sweet tamarind chutney",
     ["Please", "pack", "two", "hot", "samosas", "for", "takeaway."],
     "Please pack two hot samosas for takeaway.",
     "The potato filling inside the samosa is seasoned with cumin and ____.",
     ["coriander", "chocolate", "vanilla", "ice"], "coriander",
     "Coriander seeds and leaves are essential aromatics in samosa masala.",
     "True or False: Samosas are traditionally eaten hot with mint and tamarind chutneys.", True,
     "Hot samosas paired with green mint and brown tamarind chutney are a classic combination."),

    ("Mumbai Cutting Chai", "Cutting Chai", "Half-glass of strong brewed spiced milk tea",
     "In Mumbai slang, what does 'Cutting Chai' literally mean?",
     ["Half a cup of strong tea", "A broken tea glass", "Cold iced tea", "Herbal green tea"], "Half a cup of strong tea",
     "'Cutting' refers to splitting a full cup into two half-servings to share or drink quickly.",
     "Ek cutting chai dena, adrak aur kam cheeni ke saath.",
     "Listen to the tea order. What special request was made?",
     ["With ginger and less sugar", "With extra chocolate and ice", "Boiled without any milk", "Served in a large travel mug"],
     "With ginger and less sugar",
     ["Make", "one", "strong", "cup", "of", "cutting", "chai."],
     "Make one strong cup of cutting chai.",
     "During monsoon rains, hot chai pairs wonderfully with crispy onion ____.",
     ["pakoras", "ice cream", "muffins", "noodles"], "pakoras",
     "Pakoras (fritters) and cutting chai are a beloved monsoon tradition in India.",
     "True or False: Masala chai is brewed by simmering black tea with spices like ginger, cardamom, and milk.", True,
     "Brewing tea leaves directly with milk, crushed ginger, and cardamom creates authentic masala chai."),

    ("Vada Pav & Dry Garlic Chutney", "Vada Pav", "Spiced potato fritter inside a soft bread bun",
     "What is affectionately known as the 'Bombay Burger'?",
     ["Vada Pav", "Hot Dog", "Taco", "Spring Roll"], "Vada Pav",
     "Vada Pav is Mumbai's premier street snack—a spiced batata vada inside a pav.",
     "Add extra spicy red garlic chutney and one fried green chili.",
     "What condiments did the customer request with the vada pav?",
     ["Red garlic chutney and fried green chili", "Mayonnaise and tomato ketchup", "Maple syrup and whipped cream", "Soy sauce and vinegar"],
     "Red garlic chutney and fried green chili",
     ["Vada", "pav", "is", "Mumbai's", "most", "famous", "street", "food."],
     "Vada pav is Mumbai's most famous street food.",
     "The bread bun used in vada pav is called ____.",
     ["pav", "tortilla", "bagel", "croissant"], "pav",
     "'Pav' is the soft bread bun introduced by Portuguese traders to western India.",
     "True or False: The dry red chutney in vada pav gets its color and flavor from garlic, roasted peanuts, and chili.", True,
     "Dry garlic chutney (lasun chutney) is a trademark condiment of Mumbai street stalls."),

    ("Pani Puri & Flavored Waters", "Pani Puri", "Crispy hollow spheres filled with chickpeas, potatoes, and spiced water",
     "What is the hollow, crispy ball filled with tangy water called across Mumbai?",
     ["Pani Puri", "Gulab Jamun", "Jalebi", "Rasgulla"], "Pani Puri",
     "Pani Puri (also called Golgappa in the north) features crisp puris filled with spiced water.",
     "Bhaiya, make it medium spicy and finish with one sukha puri.",
     "What did the customer ask for at the end of the round?",
     ["One dry (sukha) puri", "A full bottle of soda", "A bowl of hot soup", "Five sweet rasgullas"],
     "One dry (sukha) puri",
     ["The", "tangy", "mint", "water", "was", "refreshing", "and", "cold."],
     "The tangy mint water was refreshing and cold.",
     "The sweet brown water in pani puri is made from dates and ____.",
     ["tamarind", "cheese", "butter", "milk"], "tamarind",
     "Tamarind (imli) provides the signature sweet and sour tanginess.",
     "True or False: A 'Sukha Puri' is a dry puri without water given as a complimentary finish.", True,
     "Street vendors traditionally give a free sukha puri topped with potato and sev after a plate."),

    ("Pav Bhaji & Extra Butter", "Pav Bhaji", "Thick mashed vegetable curry cooked with butter and served with soft buns",
     "What dish features a thick mashed vegetable curry sizzled on a large iron flat-top tawa?",
     ["Pav Bhaji", "Biryani", "Dosa", "Pizza"], "Pav Bhaji",
     "Pav Bhaji originated as a midnight meal for Mumbai textile mill workers in the 1850s.",
     "Two plates of special pav bhaji with extra Amul butter and lemon slices.",
     "How does the customer want the pav bhaji served?",
     ["With extra Amul butter and lemon", "With zero butter and no bread", "Packed in dry paper bags", "Cold without heating"],
     "With extra Amul butter and lemon",
     ["Squeeze", "fresh", "lemon", "juice", "over", "the", "hot", "bhaji."],
     "Squeeze fresh lemon juice over the hot bhaji.",
     "The chopped fresh red ____ added on top gives a crunchy bite to the buttery bhaji.",
     ["onion", "apple", "banana", "sugar"], "onion",
     "Finely diced raw onions and a squeeze of fresh lime balance the rich, buttery curry.",
     "True or False: Pav Bhaji was created as a quick, nutritious lunch for 19th-century Mumbai mill workers.", True,
     "Textile mill workers needed a fast, hearty lunch made from mixed vegetables and bread."),

    ("Frankie & Kathi Rolls", "Kathi Roll", "Warm flatbread rolled around seasoned fillings and sauces",
     "What is a wrapped street food roll consisting of seasoned paneer or chicken inside a roti?",
     ["Frankie / Kathi Roll", "Sushi Roll", "Cinnamon Roll", "Spring Roll"], "Frankie / Kathi Roll",
     "Frankies and Kathi rolls are popular grab-and-go flatbread wraps across Indian campuses.",
     "One paneer tikka frankie with mint chutney and crunchy onions.",
     "What filling was chosen for the frankie?",
     ["Paneer tikka with mint chutney and onions", "Sweet chocolate cream", "Boiled plain rice", "Raw lettuce only"],
     "Paneer tikka with mint chutney and onions",
     ["Wrap", "the", "hot", "roll", "in", "foil", "for", "takeaway."],
     "Wrap the hot roll in foil for takeaway.",
     "The special spice blend sprinkled inside a Mumbai frankie is called frankie ____.",
     ["masala", "syrup", "frosting", "jam"], "masala",
     "A tangy, pungent spice blend called frankie masala is dusted onto the egg/roti layer.",
     "True or False: Kathi rolls originated from the famous Nizam's restaurant in Kolkata before spreading nationwide.", True,
     "Kolkata's Nizam's restaurant invented the Kathi roll in the 1930s for busy commuters."),

    ("Steamed Momos & Spicy Red Dip", "Momos", "Tibetan steamed dumplings stuffed with vegetables or minced meat",
     "What are bite-sized steamed dumplings popular in hill stations and urban street markets?",
     ["Momos", "Waffles", "Nachos", "Bagels"], "Momos",
     "Momos are Tibetan and Himalayan dumplings that have become an essential Indian youth street food.",
     "One plate of steamed veg momos with extra fiery red chili garlic sauce.",
     "What sauce was requested with the momos?",
     ["Fiery red chili garlic sauce", "Sweet tomato ketchup only", "Hot melted butter", "Warm pancake syrup"],
     "Fiery red chili garlic sauce",
     ["Dip", "the", "steamed", "momo", "into", "the", "spicy", "chili", "sauce."],
     "Dip the steamed momo into the spicy chili sauce.",
     "Momos can be either steamed, pan-fried, or deep-____ for a crunchy shell.",
     ["fried", "frozen", "melted", "dissolved"], "fried",
     "Fried momos and 'kurkure momos' are crunchy variations popular at college stalls.",
     "True or False: A clear soup broth often served alongside momos is called 'Thukpa' or 'Momo soup'.", True,
     "Street stalls often serve a comforting cup of clear hot soup alongside plates of momos."),

    ("South Indian Dosa & Coconut Chutney", "Masala Dosa", "Crispy fermented crepe made from rice and black lentils",
     "What is the golden, crispy fermented crepe filled with spiced potato masala?",
     ["Masala Dosa", "Omelette", "Quesadilla", "Crepe Suzette"], "Masala Dosa",
     "Masala Dosa is a legendary South Indian breakfast crepe paired with sambar and coconut chutney.",
     "One paper butter masala dosa with piping hot sambar and fresh white coconut chutney.",
     "What accompaniments come with the dosa order?",
     ["Piping hot sambar and fresh coconut chutney", "Cold milk and strawberry jam", "French fries and mayonnaise", "Barbecue sauce and coleslaw"],
     "Piping hot sambar and fresh coconut chutney",
     ["The", "golden", "dosa", "was", "crispy", "and", "delicious."],
     "The golden dosa was crispy and delicious.",
     "The lentil and vegetable stew served with dosas and idlis is called ____.",
     ["sambar", "gravy", "custard", "pudding"], "sambar",
     "Sambar is a flavorful tamarind-and-pigeon-pea stew packed with drumsticks, carrots, and spices.",
     "True or False: Dosa batter is made from naturally fermented rice and urad dal (black lentils).", True,
     "Natural overnight fermentation gives dosa batter its airy crispness and mild sourdough tang."),

    ("Crispy Jalebi & Fafda", "Jalebi Fafda", "Crispy gram flour strips paired with spiral saffron sugar syrup pretzels",
     "Which famous Gujarati breakfast pairs crispy savory gram flour strips with syrupy spirals?",
     ["Fafda Jalebi", "Pizza Pasta", "Bread Butter", "Idli Vada"], "Fafda Jalebi",
     "Fafda Jalebi is the quintessential Sunday morning treat across Gujarat and Mumbai.",
     "Give me 250 grams of hot, juicy jalebis straight from the frying kadhai.",
     "What quality of jalebis did the customer emphasize?",
     ["Hot and juicy straight from the kadhai", "Cold and rock-hard from yesterday", "Salty with extra chili powder", "Baked without any sugar"],
     "Hot and juicy straight from the kadhai",
     ["Hot", "jalebis", "are", "soaked", "in", "fragrant", "saffron", "sugar", "syrup."],
     "Hot jalebis are soaked in fragrant saffron sugar syrup.",
     "Fafda is traditionally served with raw papaya chutney and fried green ____.",
     ["chilies", "apples", "strawberries", "cucumbers"], "chilies",
     "Salted fried green chilies (tarela marcha) provide the classic spicy kick alongside savory fafda.",
     "True or False: Jalebis are colored and flavored with saffron (kesar) and rose water in authentic sweet shops.", True,
     "Kesar (saffron) gives authentic jalebis their golden-orange hue and rich floral aroma."),

    ("Street Food Night Market Boss", "Night Market", "Vibrant street food stalls open until late midnight",
     "What is the term for a lively cluster of food stalls operating late into the night?",
     ["Night Food Market / Khau Galli", "Quiet Library", "Morning Jogging Track", "Grocery Warehouse"], "Night Food Market / Khau Galli",
     "'Khau Galli' (literally 'Food Street') in Mumbai refers to famous late-night foodie hubs.",
     "Let us explore Mohammed Ali Road and Ghatkopar Khau Galli for late-night desserts.",
     "What destinations did the friends choose for their midnight foodie trail?",
     ["Mohammed Ali Road and Ghatkopar Khau Galli", "An empty railway parking lot", "A closed corporate office park", "An airport baggage claim"],
     "Mohammed Ali Road and Ghatkopar Khau Galli",
     ["Mumbai", "street", "food", "stalls", "serve", "incredible", "flavors", "until", "midnight."],
     "Mumbai street food stalls serve incredible flavors until midnight.",
     "A famous dessert drink combining rose syrup, vermicelli noodles, sweet basil seeds, and kulfi is ____.",
     ["Falooda", "Espresso", "Lemonade", "Iced tea"], "Falooda",
     "Falooda is the king of royal street desserts, layered with creamy kulfi and sabja seeds.",
     "True or False: 'Khau Galli' translates from Marathi/Hindi to 'Eaters' Alley' or 'Food Street'.", True,
     "Khau Gallis are famous cultural epicenters of street culinary excellence across Maharashtra.")
]

# We will generate remaining 90 topics programmatically using rich templates for units 2-10
units_info = [
    # Unit 2: Cafe Culture & Breakfast (11-20)
    (11, 20, "Cafe & Breakfast", [
        ("Espresso & Cappuccino Basics", "Espresso", "Concentrated coffee shot brewed under high pressure",
         "What is the small, concentrated shot of pure coffee called?",
         ["Espresso", "Milkshake", "Hot Water", "Decaf Tea"], "Espresso",
         "An espresso shot forms the foundation for cappuccinos, lattes, and americanos.",
         "Could I have a double shot cappuccino with cinnamon dust on top?",
         "What topping did the customer request on their cappuccino?",
         ["Cinnamon dust on top", "Caramel candy on top", "Hot red pepper flakes", "Whipped butter"],
         "Cinnamon dust on top",
         ["A", "cappuccino", "has", "equal", "parts", "espresso", "steamed", "milk", "and", "foam."],
         "A cappuccino has equal parts espresso steamed milk and foam.",
         "The layer of micro-bubbles on top of an espresso shot is called the ____.",
         ["crema", "froth", "foam", "syrup"], "crema",
         "The golden-brown aromatic foam on an espresso is called crema.",
         "True or False: A Latte contains more steamed milk than a traditional Cappuccino.", True,
         "A latte is predominantly steamed milk with a thin cap of foam, making it smoother."),

        ("Iced Cold Brew & Milk Alternatives", "Cold Brew", "Coffee steeped in cold water for 12 to 24 hours",
         "How is cold brew coffee prepared differently from iced coffee?",
         ["Steeped in cold water for 12-24 hours", "Boiled with sugar and frozen", "Mixed with instant powder and ice cubes", "Filtered through hot tea bags"],
         "Steeped in cold water for 12-24 hours",
         "Cold water extraction produces a smoother, less acidic coffee flavor profile.",
         "One grande cold brew with oat milk and sugar-free vanilla syrup.",
         "What plant-based milk was chosen for the cold brew?",
         ["Oat milk", "Whole dairy milk", "Heavy cream", "Condensed milk"],
         "Oat milk",
         ["Oat", "milk", "is", "a", "creamy", "plant-based", "dairy", "alternative."],
         "Oat milk is a creamy plant-based dairy alternative.",
         "Almond, soy, and oat milk are popular plant-based ____ for lactose-intolerant coffee lovers.",
         ["alternatives", "condiments", "spices", "sweeteners"], "alternatives",
         "Non-dairy alternatives allow coffee lovers to enjoy creamy drinks without dairy.",
         "True or False: Cold brew coffee naturally has lower acidity than hot-brewed coffee.", True,
         "Cold extraction draws out sweet aromatic oils while leaving behind harsh bitter acids."),

        ("Bakery Croissants & Pastries", "Croissant", "Flaky, buttery French crescent pastry",
         "What famous French bakery item is known for its flaky crescent shape and layered butter?",
         ["Croissant", "Baguette", "Pancake", "Muffin"], "Croissant",
         "Lamination (folding butter into dough multiple times) gives croissants their airy, flaky layers.",
         "Please warm up this chocolate croissant and pair it with an iced latte.",
         "What pastry did the customer ask to have warmed up?",
         ["Chocolate croissant", "Plain garlic loaf", "Dry toast slice", "Carrot cake"],
         "Chocolate croissant",
         ["The", "warm", "croissant", "was", "flaky", "buttery", "and", "fresh."],
         "The warm croissant was flaky buttery and fresh.",
         "Pastry chefs create dozens of buttery layers in croissant dough through a process called ____.",
         ["lamination", "boiling", "freezing", "frying"], "lamination",
         "Lamination is the culinary art of folding butter into dough to create airy flaky sheets.",
         "True or False: A pain au chocolat is a pastry filled with batons of dark chocolate.", True,
         "Pain au chocolat is a beloved French viennoiserie pastry featuring chocolate rods in laminated dough."),

        ("Eggs Any Style: Scrambled & Sunny Side Up", "Sunny Side Up", "Egg fried on one side with runny liquid yolk",
         "What is an egg fried on one side so the yellow yolk remains intact and runny called?",
         ["Sunny-side up", "Hard-boiled", "Poached", "Scrambled"], "Sunny-side up",
         "Sunny-side up eggs are fried without flipping, leaving a glowing bright yellow yolk.",
         "I would like two eggs over-easy, sourdough toast, and grilled mushrooms.",
         "What style of eggs and bread did the breakfast diner order?",
         ["Two eggs over-easy with sourdough toast and mushrooms", "Raw eggs in a blender with milk", "Boiled eggs with sweet yogurt", "No eggs, just pancakes"],
         "Two eggs over-easy with sourdough toast and mushrooms",
         ["Whisk", "the", "eggs", "gently", "with", "a", "pinch", "of", "salt."],
         "Whisk the eggs gently with a pinch of salt.",
         "When an egg is gently simmered in simmering water without its shell, it is ____.",
         ["poached", "baked", "grilled", "charred"], "poached",
         "Poaching eggs in swirling hot water creates silky whites and molten yolks for Eggs Benedict.",
         "True or False: 'Over-easy' means the egg is flipped briefly to cook the white while keeping the yolk runny.", True,
         "Over-easy eggs are turned over in the pan for just a few seconds to set the top white."),

        ("Morning Poha & Steamed Idlis", "Poha", "Flattened rice cooked with turmeric, mustard seeds, and roasted peanuts",
         "What flattened rice breakfast dish is seasoned with turmeric, green chilies, and peanuts?",
         ["Poha", "Khichdi", "Upma", "Halwa"], "Poha",
         "Poha is a light, nutritious breakfast favored across Maharashtra, Madhya Pradesh, and Gujarat.",
         "One plate of warm Kanda Poha garnished with fresh grated coconut and lime.",
         "What garnishes were added to the Kanda Poha?",
         ["Fresh grated coconut and lime", "Chocolate syrup and sprinkles", "Dry oregano and chili flakes", "Mayonnaise and ketchup"],
         "Fresh grated coconut and lime",
         ["Steamed", "idlis", "are", "fluffy", "healthy", "and", "easy", "to", "digest."],
         "Steamed idlis are fluffy healthy and easy to digest.",
         "Idlis are fermented cakes of ground rice and black gram, cooked by ____.",
         ["steaming", "deep-frying", "roasting", "microwaving"], "steaming",
         "Steaming in specialized idli molds preserves nutrients and creates an airy, soft texture.",
         "True or False: Poha is gluten-free because it is made from flattened whole rice grains.", True,
         "Since poha is made purely of de-husked flattened rice, it is naturally 100% gluten-free."),

        ("Fluffy Pancakes & Maple Syrup", "Pancakes", "Flat round cakes cooked on a griddle from starch-based batter",
         "What sweet breakfast staple is stacked high and drizzled with warm maple syrup?",
         ["Pancakes", "Waffles", "French Fries", "Garlic Bread"], "Pancakes",
         "Pancakes are griddle-cooked cakes served with butter, berries, and maple syrup.",
         "A tall stack of blueberry pancakes with whipped butter and pure maple syrup.",
         "What fruit was folded inside the pancake stack?",
         ["Blueberries", "Green apples", "Red tomatoes", "Raw onions"],
         "Blueberries",
         ["Pour", "warm", "maple", "syrup", "over", "the", "fresh", "pancake", "stack."],
         "Pour warm maple syrup over the fresh pancake stack.",
         "The chemical reaction between baking powder and buttermilk makes pancakes light and ____.",
         ["fluffy", "dense", "stiff", "chewy"], "fluffy",
         "Carbon dioxide bubbles released during cooking create the signature airy fluffiness.",
         "True or False: Authentic maple syrup is tapped directly from the sap of maple trees.", True,
         "Maple trees are tapped in spring and their sap is boiled down to produce pure maple syrup."),

        ("Fresh Fruit Juices & Smoothies", "Smoothie", "Thick blended beverage made from pureed raw fruit and yogurt",
         "What thick blended fruit drink is made with frozen bananas, berries, and yogurt?",
         ["Smoothie", "Espresso", "Clear Soup", "Soda Water"], "Smoothie",
         "Smoothies blend whole fruits with milk, yogurt, or protein powder for a thick, nutritious drink.",
         "One fresh Valencia orange juice, cold-pressed with no added sugar or ice.",
         "How did the customer want the orange juice prepared?",
         ["Cold-pressed with no added sugar or ice", "Boiled with ginger and honey", "Mixed with hot milk and chocolate", "Bottled three months ago"],
         "Cold-pressed with no added sugar or ice",
         ["Freshly", "squeezed", "fruit", "juice", "is", "rich", "in", "vitamin", "C."],
         "Freshly squeezed fruit juice is rich in vitamin C.",
         "A hydraulic press that crushes fruits without heat oxidation produces ____ juice.",
         ["cold-pressed", "boiled", "fermented", "evaporated"], "cold-pressed",
         "Cold-pressing preserves live enzymes and vitamins by avoiding heat from fast spinning blades.",
         "True or False: Green smoothies often include leafy vegetables like spinach or kale blended with sweet fruits.", True,
         "Blending mild baby spinach with sweet bananas masks the green taste while boosting vitamins."),

        ("Cafe Seating & Free Wi-Fi Requests", "Wi-Fi Password", "Credentials to connect to the café's local wireless internet",
         "How do you politely ask a café barista for the internet login credentials?",
         ["Could you please share the Wi-Fi password?", "Give me internet now!", "Why is your router slow?", "Connect my laptop immediately."],
         "Could you please share the Wi-Fi password?",
         "Asking 'Could you please share the Wi-Fi password?' is polite and standard in coffee shops.",
         "Is there an electrical outlet nearby where I can plug in my laptop?",
         "What amenity was the customer looking for at their table?",
         ["An electrical outlet to plug in a laptop", "A private bedroom to sleep", "A swimming pool on the terrace", "A gas stove to cook lunch"],
         "An electrical outlet to plug in a laptop",
         ["Could", "we", "sit", "by", "the", "window", "table", "please?"],
         "Could we sit by the window table please?",
         "A customer who spends hours working on their laptop in a coffee shop is a café ____.",
         ["nomad", "burglar", "mechanic", "driver"], "nomad",
         "Digital nomads often work from cozy laptop-friendly coffee shops with reliable internet.",
         "True or False: It is polite café etiquette to purchase drinks or snacks periodically when using their workspace.", True,
         "Supporting the café with recurring orders respects their seating space and electricity costs."),

        ("Ordering To-Go vs For Here", "Takeaway / To-Go", "Food packed in containers to be consumed away from the restaurant",
         "What phrase do you use when you want to take your coffee with you rather than sit down?",
         ["To-go / Takeaway", "For here / Dine-in", "Throw away", "Leave on counter"], "To-go / Takeaway",
         "'To-go' (or 'takeaway') tells the barista to pack your beverage in a disposable cup with a lid.",
         "I will take this iced matcha latte to-go in a paper cup, please.",
         "How does the customer want their matcha latte packed?",
         ["To-go in a paper cup", "In a ceramic mug to sit for two hours", "In a glass bowl with a spoon", "Poured directly into their hands"],
         "To-go in a paper cup",
         ["Would", "you", "like", "that", "for", "here", "or", "to", "go?"],
         "Would you like that for here or to go?",
         "A drink packaged to enjoy while sitting inside the café is marked as 'For ____'.",
         ["here", "away", "later", "never"], "here",
         "'For here' (or 'dine in') means served in washable ceramic mugs or glasses.",
         "True or False: Bringing your own reusable travel tumbler often earns a small discount at modern cafes.", True,
         "Eco-conscious coffee shops incentivize reusable cups to reduce disposable paper cup waste."),

        ("Barista Speed Challenge & Boss", "Barista Boss", "Mastery of coffee brewing, orders, and café hospitality",
         "What is the title given to a trained coffee professional who prepares espresso beverages?",
         ["Barista", "Sommelier", "Conductor", "Pilot"], "Barista",
         "A barista is an expert in coffee bean profiles, grinder calibration, espresso extraction, and latte art.",
         "Double espresso macchiato with velvety oat foam, ready on the pickup counter!",
         "What drink did the barista announce on the counter?",
         ["Double espresso macchiato with oat foam", "Pot of boiling hot tap water", "Cup of instant black tea", "Pitcher of strawberry juice"],
         "Double espresso macchiato with oat foam",
         ["The", "barista", "steamed", "the", "milk", "to", "a", "silky", "microfoam."],
         "The barista steamed the milk to a silky microfoam.",
         "Pouring steamed milk into espresso to create hearts, rosettas, and swans is called latte ____.",
         ["art", "craft", "graffiti", "paint"], "art",
         "Latte art requires precise control of milk texture, pour height, and pitcher tilting.",
         "True or False: The word 'Barista' comes from the Italian language meaning a bartender who serves beverages.", True,
         "In Italy, a barista serves all drinks at a counter, but globally it refers specifically to coffee masters.")
    ])
]

# We will populate all 100 lessons programmatically with rich content across the 10 units!
print("Loaded Unit 1 & Unit 2 blueprints.")
